### PR TITLE
Set targets to fix "Module not loadable on target mobile" warnings

### PR DESCRIPTION
**Pull request by jdlrobson**
Hey @matthiasmullie can you take a look at this? Not sure what this module is for, but it's showing up in error logs as part of https://phabricator.wikimedia.org/T324723.

Thanks in advance!

### CODE REVIEW

**Comment by jdlrobson** [comment]
@matthiasmullie I'm also having issues pushing this to gerrit so I am a little confused with where the source of truth is for this code!

**Comment by jdlrobson** [comment]
Looks like I just had to run  `git review master` (it was defaulting to main)

**Comment by jdlrobson** [comment]
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/ImageSuggestions/+/867259

**Comment by matthiasmullie** [comment]
FYI: this repo was first created with "main" as its main branch; that got changed back to "master" over translatewiki incompatibilities. Looks like there's still some leftover stuff though.

Anyway - thanks for the patch, merged!

**Pull request closed without merging**
